// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgx6jXQxmqM-oKkTYxUwjAkxme_9k-lbk',
    appId: '1:492423915935:web:0881c6d8cbaa83533ff5aa',
    messagingSenderId: '492423915935',
    projectId: 'evirgenotomasyon-a3067',
    authDomain: 'evirgenotomasyon-a3067.firebaseapp.com',
    databaseURL: 'https://evirgenotomasyon-a3067-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'evirgenotomasyon-a3067.appspot.com',
    measurementId: 'G-Z6V30F0V3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2pJGsSQcj3Uy_tT3oC0BHd0foQTt5fdY',
    appId: '1:492423915935:android:dc39829ad5512b513ff5aa',
    messagingSenderId: '492423915935',
    projectId: 'evirgenotomasyon-a3067',
    databaseURL: 'https://evirgenotomasyon-a3067-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'evirgenotomasyon-a3067.appspot.com',
  );
}
